### ISSUE TITLE
Create outputDirectory if it doesn't exist

### ISSUE THREAD

**Issue by briacp** [dependency-check/dependency-check-gradle#277]
Hello,

Currently, if I set `outputDirectory = 'build/reports/owasp-dependencycheck'` and the directory does not exists, the reports are (silently) not created.

Is there a reason not to create the output directory if it does not exist ?

I think it would make sense in [AbstractAnalyze](https://github.com/dependency-check/dependency-check-gradle/blob/main/src/main/groovy/org/owasp/dependencycheck/gradle/tasks/AbstractAnalyze.groovy#L104), after obtaining the output directory it would make sense to add `output.mkdirs()`.

**Comment by jeremylong** [comment]
I'm betting the reports are created - just not where you expected them ;)

If the directory does not exist it is created here: https://github.com/jeremylong/DependencyCheck/blob/21cd89bdc2531632e18d0b0e085c6d85112853d0/core/src/main/java/org/owasp/dependencycheck/reporting/ReportGenerator.java#L480

Due to the line here:
https://github.com/jeremylong/DependencyCheck/blob/21cd89bdc2531632e18d0b0e085c6d85112853d0/core/src/main/java/org/owasp/dependencycheck/reporting/ReportGenerator.java#L405

If you run with `-info` you should see the logging messages showing where the reports were being written. You likely want to update your configuration to:

```
outputDirectory = '${buildDir}/reports/owasp-dependencycheck'
```

I've updated the documentation to be more clear on this: https://github.com/jeremylong/DependencyCheck/pull/4871

**Comment by briacp** [comment]
Awesome, thanks! Indeed should have dug deeper into the ReportGenerator 💯
